### ISSUE TITLE
Cannot start kak-lsp Mac OS X

### ISSUE THREAD

**Issue by Hittherhod** [ul/kak-lsp#172]
I'm trying to use kak-lsp with the homebrew installation of kakoune on Mac OS X but kak-lsp is always erroring out. I get the following error using version 6.0.1 (with RUST_BACKTRACE=1)

```
thread 'main' panicked at 'Failed to parse config file: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "missing field `filetypes`", key: ["language", "rust"] } }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:312
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/146aa60f3484d8267e085e80611969f387eca068/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::expect
             at /rustc/146aa60f3484d8267e085e80611969f387eca068/src/libcore/result.rs:825
  10: kak_lsp::main
             at src/main.rs:151
  11: std::rt::lang_start::{{closure}}
             at /rustc/146aa60f3484d8267e085e80611969f387eca068/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  14: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/146aa60f3484d8267e085e80611969f387eca068/src/libstd/rt.rs:64
  16: kak_lsp::spin_up_server
```

I haven't modified the configuration file and it matches what is in the repo, but I still get this issue. I have the same problem with the master branch from git.

**Comment by ul** [comment]
Did you use kak-lsp before? Could it be the case that you have `kak-lsp.toml` leftover in `~/.config/kak-lsp/` in pre-v6 format?

**Comment by Hittherhod** [comment]
I had used it before. That was it. Thanks!
