### ISSUE TITLE
attempt to subtract with overflow in position.rs

### ISSUE THREAD

**Issue by ricochet1k** [ul/kak-lsp#200]
In experimenting with the CodeAction support #199 I hit this error trying to automatically insert a `use`.

```
May 07 15:43:21.306 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":34,"line":171},"textDocument":{"uri":"file:///home/user/kak-lsp/src/controller.rs"}},"id":10}, module: kak_lsp::language_server_transport:149
May 07 15:43:21.322 DEBG From server: {"jsonrpc":"2.0","id":10,"result":{"contents":[],"range":{"start":{"line":171,"character":27},"end":{"line":171,"character":38}}}}, module: kak_lsp::language_server_transport:129
May 07 15:43:21.323 DEBG To editor `27029`: eval -client client0 'lsp-show-hover 172.35 ''• cannot find trait `Deserialize` in this scope

not found in this scope''', module: kak_lsp::editor_transport:83
May 07 15:43:22.332 DEBG From editor: 
session   = "27029"
client    = "client0"
buffile   = "/home/user/kak-lsp/src/controller.rs"
filetype  = "rust"
version   = 1
method    = "textDocument/codeAction"
[params.position]
line      = 172
column    = 35
, module: kak_lsp::editor_transport:153
May 07 15:43:22.335 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_RUST, module: kak_lsp::project_root:41
May 07 15:43:22.335 DEBG Routing editor request to Route { session: "27029", language: "rust", root: "/home/user/kak-lsp" }, module: kak_lsp::session:117
May 07 15:43:22.335 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":34,"line":171},"start":{"character":34,"line":171}},"textDocument":{"uri":"file:///home/user/kak-lsp/src/controller.rs"}},"id":11}, module: kak_lsp::language_server_transport:149
May 07 15:43:22.335 DEBG From server: {"jsonrpc":"2.0","id":11,"result":[{"title":"Line 1: Add `use serde::Deserialize;\n`","command":"rls.applySuggestion-27182","arguments":[{"range":{"end":{"character":0,"line":0},"start":{"character":0,"line":0}},"uri":"file:///home/user/kak-lsp/src/controller.rs"},"use serde::Deserialize;\n"]},{"title":"Line 1: Add `use serde::de::Deserialize;\n`","command":"rls.applySuggestion-27182","arguments":[{"range":{"end":{"character":0,"line":0},"start":{"character":0,"line":0}},"uri":"file:///home/user/kak-lsp/src/controller.rs"},"use serde::de::Deserialize;\n"]},{"title":"Line 1: Add `use toml::macros::Deserialize;\n`","command":"rls.applySuggestion-27182","arguments":[{"range":{"end":{"character":0,"line":0},"start":{"character":0,"line":0}},"uri":"file:///home/user/kak-lsp/src/controller.rs"},"use toml::macros::Deserialize;\n"]}]}, module: kak_lsp::language_server_transport:129
May 07 15:43:22.337 DEBG Command: Command { title: "Line 1: Add `use serde::Deserialize;\n`", command: "rls.applySuggestion-27182", arguments: Some([Object({"range": Object({"end": Object({"character": Number(0), "line": Number(0)}), "start": Object({"character": Number(0), "line": Number(0)})}), "uri": String("file:///home/user/kak-lsp/src/controller.rs")}), String("use serde::Deserialize;\n")]) }, module: kak_lsp::language_features::codeaction:48
May 07 15:43:22.337 DEBG Command: Command { title: "Line 1: Add `use serde::de::Deserialize;\n`", command: "rls.applySuggestion-27182", arguments: Some([Object({"range": Object({"end": Object({"character": Number(0), "line": Number(0)}), "start": Object({"character": Number(0), "line": Number(0)})}), "uri": String("file:///home/user/kak-lsp/src/controller.rs")}), String("use serde::de::Deserialize;\n")]) }, module: kak_lsp::language_features::codeaction:48
May 07 15:43:22.337 DEBG Command: Command { title: "Line 1: Add `use toml::macros::Deserialize;\n`", command: "rls.applySuggestion-27182", arguments: Some([Object({"range": Object({"end": Object({"character": Number(0), "line": Number(0)}), "start": Object({"character": Number(0), "line": Number(0)})}), "uri": String("file:///home/user/kak-lsp/src/controller.rs")}), String("use toml::macros::Deserialize;\n")]) }, module: kak_lsp::language_features::codeaction:48
May 07 15:43:22.338 DEBG To editor `27029`: eval -client client0 'menu ''Line 1: Add `use serde::Deserialize;
`'' ''lsp-execute-command ''''rls.applySuggestion-27182'''' ''''"[{\"range\":{\"end\":{\"character\":0,\"line\":0},\"start\":{\"character\":0,\"line\":0}},\"uri\":\"file:///home/user/kak-lsp/src/controller.rs\"},\"use serde::Deserialize;\\n\"]"'''''' ''Line 1: Add `use serde::de::Deserialize;
`'' ''lsp-execute-command ''''rls.applySuggestion-27182'''' ''''"[{\"range\":{\"end\":{\"character\":0,\"line\":0},\"start\":{\"character\":0,\"line\":0}},\"uri\":\"file:///home/user/kak-lsp/src/controller.rs\"},\"use serde::de::Deserialize;\\n\"]"'''''' ''Line 1: Add `use toml::macros::Deserialize;
`'' ''lsp-execute-command ''''rls.applySuggestion-27182'''' ''''"[{\"range\":{\"end\":{\"character\":0,\"line\":0},\"start\":{\"character\":0,\"line\":0}},\"uri\":\"file:///home/user/kak-lsp/src/controller.rs\"},\"use toml::macros::Deserialize;\\n\"]"''''''', module: kak_lsp::editor_transport:83
May 07 15:43:31.644 DEBG From editor: 
session   = "27029"
client    = "client0"
buffile   = "/home/user/kak-lsp/src/controller.rs"
filetype  = "rust"
version   = 1
method    = "workspace/executeCommand"
[params]
command = "rls.applySuggestion-27182"
arguments = "[{\"range\":{\"end\":{\"character\":0,\"line\":0},\"start\":{\"character\":0,\"line\":0}},\"uri\":\"file:///home/user/kak-lsp/src/controller.rs\"},\"use serde::Deserialize;\\n\"]"
, module: kak_lsp::editor_transport:153
May 07 15:43:31.645 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_RUST, module: kak_lsp::project_root:41
May 07 15:43:31.645 DEBG Routing editor request to Route { session: "27029", language: "rust", root: "/home/user/kak-lsp" }, module: kak_lsp::session:117
May 07 15:43:31.647 DEBG To server: {"jsonrpc":"2.0","method":"workspace/executeCommand","params":{"arguments":[{"range":{"end":{"character":0,"line":0},"start":{"character":0,"line":0}},"uri":"file:///home/user/kak-lsp/src/controller.rs"},"use serde::Deserialize;\n"],"command":"rls.applySuggestion-27182"},"id":12}, module: kak_lsp::language_server_transport:149
May 07 15:43:31.647 DEBG From server: {"jsonrpc":"2.0","method":"workspace/applyEdit","id":2,"params":{"edit":{"changes":{"file:///home/user/kak-lsp/src/controller.rs":[{"newText":"use serde::Deserialize;\n","range":{"end":{"character":0,"line":0},"start":{"character":0,"line":0}}}]}}}}, module: kak_lsp::language_server_transport:129
May 07 15:43:31.647 DEBG From server: {"jsonrpc":"2.0","id":12,"result":null}, module: kak_lsp::language_server_transport:129
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/position.rs:108:9
May 07 15:43:31.729 DEBG From editor: 
session   = "27029"
client    = "client0"
buffile   = "/home/user/kak-lsp/src/controller.rs"
filetype  = "rust"
version   = 1
method    = "textDocument/hover"
[params.position]
line      = 172
column    = 35
, module: kak_lsp::editor_transport:153
May 07 15:43:31.730 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_RUST, module: kak_lsp::project_root:41
May 07 15:43:31.730 DEBG Routing editor request to Route { session: "27029", language: "rust", root: "/home/user/kak-lsp" }, module: kak_lsp::session:117
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: kak_lsp::position::lsp_range_to_kakoune_utf_8_code_units
             at src/position.rs:108
  10: kak_lsp::position::lsp_range_to_kakoune_utf_8_code_points
             at src/position.rs:77
  11: kak_lsp::position::lsp_range_to_kakoune
             at src/position.rs:42
  12: kak_lsp::text_edit::lsp_text_edit_to_kakoune
             at src/text_edit.rs:252
  13: kak_lsp::text_edit::apply_text_edits_to_buffer::{{closure}}
             at src/text_edit.rs:142
  14: <core::iter::adapters::Map<I, F> as core::iter::traits::iterator::Iterator>::fold::{{closure}}
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/iter/adapters/mod.rs:587
  15: <core::slice::Iter<'a, T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/slice/mod.rs:3003
  16: <core::iter::adapters::Map<I, F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/iter/adapters/mod.rs:587
  17: core::iter::traits::iterator::Iterator::for_each
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/iter/traits/iterator.rs:604
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/liballoc/vec.rs:1852
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/liballoc/vec.rs:1835
  20: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/liballoc/vec.rs:1721
  21: core::iter::traits::iterator::Iterator::collect
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/iter/traits/iterator.rs:1465
  22: kak_lsp::text_edit::apply_text_edits_to_buffer
             at src/text_edit.rs:140
  23: kak_lsp::util::apply_text_edits
             at src/util.rs:236
  24: kak_lsp::workspace::apply_edit
             at src/workspace.rs:141
  25: kak_lsp::controller::dispatch_server_request
             at src/controller.rs:258
  26: kak_lsp::controller::start
             at src/controller.rs:99
  27: kak_lsp::session::spawn_controller::{{closure}}
             at src/session.rs:215
```

**Comment by ul** [comment]
Though zero-length ranges are generally valid in LSP, `"range":{"end":{"character":0,"line":0},"start":{"character":0,"line":0}}` is not a valid one because

* LSP ranges are exclusive, so even zero-length range's end must point to the next character, not the same as start;
* by pointing to the 0th character of the 0th line it ends on the line -1 according to the spec:

> A range in a text document expressed as (zero-based) start and end positions. A range is comparable to a selection in an editor. Therefore the end position is exclusive. If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line.

I think it worth raising an RLS issue for it, but if this spec violation is widespread we might want to adopt a workaround.

**Comment by ul** [comment]
I think I was wrong, `range.start == range.end` is a valid case, and it seems that for the beginning of line `end` just should be processed specially. Spec is not very clear about it, but it seems the only reasonable interpretation for insertion.
