### ISSUE TITLE
Haxe LSP `data did not match any variant of untagged enum CompletionResponse`

### ISSUE THREAD

**Issue by Jumblemuddle** [ul/kak-lsp#204]
I'm attempting to integrate with [Haxe LSP](https://github.com/vshaxe/haxe-language-server), but it seems like it returns completion data in a different format than expected.

```
May 30 14:16:19.552 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_HAXE, module: kak_lsp::project_root:41
May 30 14:16:19.552 DEBG Routing editor request to Route { session: "1725", language: "haxe", root: "/home/garrett/tmp" }, module: kak_lsp::session:117
May 30 14:16:19.552 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"import Sys;\n\nclass Main {\n  static public function main(): Void {\n    \"asdf\".\n    trace(\"asdf\");\n    Sys.exit(1);\n  }\n}\n"}],"textDocument":{"uri":"file:///home/garrett/tmp/Main.hx","version":19}}}, module: kak_lsp::language_server_transport:149
May 30 14:16:19.559 DEBG From editor:
session   = "1725"
client    = "client0"
buffile   = "/home/garrett/tmp/Main.hx"
filetype  = "haxe"
version   = 19
method    = "textDocument/completion"
[params.position]
line      = 5
column    = 12
[params.completion]
offset    = 1
, module: kak_lsp::editor_transport:153
May 30 14:16:19.559 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_HAXE, module: kak_lsp::project_root:41
May 30 14:16:19.559 DEBG Routing editor request to Route { session: "1725", language: "haxe", root: "/home/garrett/tmp" }, module: kak_lsp::session:117
May 30 14:16:19.559 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":11,"line":4},"textDocument":{"uri":"file:///home/garrett/tmp/Main.hx"}},"id":6}, module: kak_lsp::language_server_transport:149
May 30 14:16:19.568 DEBG From server: {"jsonrpc":"2.0","id":6,"result":[{"label":"for","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"for (${1:i} in \"asdf\") {\n\t$0\n}","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"for (item in expr)"},{"label":"for k=>v","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"for (key => value in \"asdf\") {\n\t$0\n}","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"for (key => value in expr)"},{"label":"trace","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"trace(${1:\"asdf\"});","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"trace(expr);"},{"label":"print","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"Sys.println(${1:\"asdf\"});","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"Sys.println(expr);"},{"label":"is","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"Std.is(\"asdf\", $1)","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"Std.is(expr, T)","command":{"title":"Trigger Suggest","command":"editor.action.triggerSuggest","arguments":[]}},{"label":"unsafe cast","sortText":"~","kind":15,"insertTextFormat":1,"textEdit":{"newText":"cast \"asdf\"","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"cast expr"},{"label":"safe cast","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"cast(\"asdf\", $1)","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"cast(expr, T)","command":{"title":"Trigger Suggest","command":"editor.action.triggerSuggest","arguments":[]}},{"label":"type check","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"(\"asdf\" : $1)","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"(expr : T)","command":{"title":"Trigger Suggest","command":"editor.action.triggerSuggest","arguments":[]}},{"label":"null","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"if (\"asdf\" == null) {\n\t$0\n}","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"if (expr == null)"},{"label":"not null","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"if (\"asdf\" != null) {\n\t$0\n}","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"if (expr != null)"},{"label":"return","sortText":"~","kind":15,"insertTextFormat":1,"textEdit":{"newText":"return \"asdf\";","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"return expr;"},{"label":"var","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"var ${1:name} = \"asdf\";","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"var name = \"asdf\";"},{"label":"final","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"final ${1:name} = \"asdf\";","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"detail":"final name = \"asdf\";"},{"label":"for 0...\"asdf\".length","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"for (i in 0...\"asdf\".length) {\n\t$0\n}","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"documentation":{"kind":"markdown","value":"```haxe\nfor (i in 0...\"asdf\".length) {\n\t|\n}\n```"}},{"label":"while 0...\"asdf\".length","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"var i = 0;\nwhile (i < \"asdf\".length) {\n\t$0\n\ti++;\n}","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"documentation":{"kind":"markdown","value":"```haxe\nvar i = 0;\nwhile (i < \"asdf\".length) {\n\t|\n\ti++;\n}\n```"}},{"label":"while \"asdf\".length...0","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"var i = \"asdf\".length;\nwhile (i-- > 0) {\n\t$0\n}","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"documentation":{"kind":"markdown","value":"```haxe\nvar i = \"asdf\".length;\nwhile (i-- > 0) {\n\t|\n}\n```"}},{"label":"switch","sortText":"~","kind":15,"insertTextFormat":2,"textEdit":{"newText":"switch \"asdf\" {\n\tcase $0\n}","range":{"start":{"character":11,"line":4},"end":{"character":11,"line":4}}},"additionalTextEdits":[{"range":{"start":{"line":4,"character":4},"end":{"character":11,"line":4}},"newText":""}],"data":{"origin":1},"documentation":{"kind":"markdown","value":"```haxe\nswitch \"asdf\" {\n\tcase |\n}\n```"},"detail":"switch expr {cases...}","command":{"title":"Trigger Suggest","command":"editor.action.triggerSuggest","arguments":[]}},{"label":"charAt","kind":2,"detail":"public function charAt(index:Int):String","textEdit":{"newText":"charAt"},"documentation":null,"sortText":"0000000001","data":{"origin":0,"index":0}},{"label":"charCodeAt","kind":2,"detail":"public function charCodeAt(index:Int):Null<Int>","textEdit":{"newText":"charCodeAt"},"documentation":null,"sortText":"0000000002","data":{"origin":0,"index":1}},{"label":"indexOf","kind":2,"detail":"public function indexOf(str:String, ?startIndex:Null<Int>):Int","textEdit":{"newText":"indexOf"},"documentation":null,"sortText":"0000000003","data":{"origin":0,"index":2}},{"label":"iterator","kind":2,"detail":"public inline function iterator():haxe.iterators.StringIterator","textEdit":{"newText":"iterator"},"documentation":null,"sortText":"0000000004","data":{"origin":0,"index":3}},{"label":"keyValueIterator","kind":2,"detail":"public inline function keyValueIterator():haxe.iterators.StringKeyValueIterator","textEdit":{"newText":"keyValueIterator"},"documentation":null,"sortText":"0000000005","data":{"origin":0,"index":4}},{"label":"lastIndexOf","kind":2,"detail":"public function lastIndexOf(str:String, ?startIndex:Null<Int>):Int","textEdit":{"newText":"lastIndexOf"},"documentation":null,"sortText":"0000000006","data":{"origin":0,"index":5}},{"label":"length","kind":10,"detail":"public var length(default, null):Int","textEdit":{"newText":"length"},"documentation":null,"sortText":"0000000007","data":{"origin":0,"index":6}},{"label":"split","kind":2,"detail":"public function split(delimiter:String):Array<String>","textEdit":{"newText":"split"},"documentation":null,"sortText":"0000000008","data":{"origin":0,"index":7}},{"label":"substr","kind":2,"detail":"public function substr(pos:Int, ?len:Null<Int>):String","textEdit":{"newText":"substr"},"documentation":null,"sortText":"0000000009","data":{"origin":0,"index":8}},{"label":"substring","kind":2,"detail":"public function substring(startIndex:Int, ?endIndex:Null<Int>):String","textEdit":{"newText":"substring"},"documentation":null,"sortText":"0000000010","data":{"origin":0,"index":9}},{"label":"toLowerCase","kind":2,"detail":"public function toLowerCase():String","textEdit":{"newText":"toLowerCase"},"documentation":null,"sortText":"0000000011","data":{"origin":0,"index":10}},{"label":"toString","kind":2,"detail":"public function toString():String","textEdit":{"newText":"toString"},"documentation":null,"sortText":"0000000012","data":{"origin":0,"index":11}},{"label":"toUpperCase","kind":2,"detail":"public function toUpperCase():String","textEdit":{"newText":"toUpperCase"},"documentation":null,"sortText":"0000000013","data":{"origin":0,"index":12}}]}, module: kak_lsp::language_server_transport:129
thread '<unnamed>' panicked at 'Failed to parse response: Error("data did not match any variant of untagged enum CompletionResponse", line: 0, column: 0)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
May 30 14:16:19.569 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:160
May 30 14:16:19.569 ERRO Failed to join controller thread, module: kak_lsp::session:75
```

**Comment by Jumblemuddle** [comment]
<details>
  <summary>Here's the JSON</summary>

```
{
  "jsonrpc": "2.0",
  "id": 6,
  "result": [
    {
      "label": "for",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "for (${1:i} in \"asdf\") {\n\t$0\n}",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "for (item in expr)"
    },
    {
      "label": "for k=>v",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "for (key => value in \"asdf\") {\n\t$0\n}",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "for (key => value in expr)"
    },
    {
      "label": "trace",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "trace(${1:\"asdf\"});",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "trace(expr);"
    },
    {
      "label": "print",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "Sys.println(${1:\"asdf\"});",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "Sys.println(expr);"
    },
    {
      "label": "is",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "Std.is(\"asdf\", $1)",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "Std.is(expr, T)",
      "command": {
        "title": "Trigger Suggest",
        "command": "editor.action.triggerSuggest",
        "arguments": []
      }
    },
    {
      "label": "unsafe cast",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 1,
      "textEdit": {
        "newText": "cast \"asdf\"",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "cast expr"
    },
    {
      "label": "safe cast",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "cast(\"asdf\", $1)",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "cast(expr, T)",
      "command": {
        "title": "Trigger Suggest",
        "command": "editor.action.triggerSuggest",
        "arguments": []
      }
    },
    {
      "label": "type check",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "(\"asdf\" : $1)",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "(expr : T)",
      "command": {
        "title": "Trigger Suggest",
        "command": "editor.action.triggerSuggest",
        "arguments": []
      }
    },
    {
      "label": "null",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "if (\"asdf\" == null) {\n\t$0\n}",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "if (expr == null)"
    },
    {
      "label": "not null",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "if (\"asdf\" != null) {\n\t$0\n}",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "if (expr != null)"
    },
    {
      "label": "return",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 1,
      "textEdit": {
        "newText": "return \"asdf\";",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "return expr;"
    },
    {
      "label": "var",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "var ${1:name} = \"asdf\";",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "var name = \"asdf\";"
    },
    {
      "label": "final",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "final ${1:name} = \"asdf\";",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "detail": "final name = \"asdf\";"
    },
    {
      "label": "for 0...\"asdf\".length",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "for (i in 0...\"asdf\".length) {\n\t$0\n}",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "documentation": {
        "kind": "markdown",
        "value": "```haxe\nfor (i in 0...\"asdf\".length) {\n\t|\n}\n```"
      }
    },
    {
      "label": "while 0...\"asdf\".length",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "var i = 0;\nwhile (i < \"asdf\".length) {\n\t$0\n\ti++;\n}",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "documentation": {
        "kind": "markdown",
        "value": "```haxe\nvar i = 0;\nwhile (i < \"asdf\".length) {\n\t|\n\ti++;\n}\n```"
      }
    },
    {
      "label": "while \"asdf\".length...0",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "var i = \"asdf\".length;\nwhile (i-- > 0) {\n\t$0\n}",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "documentation": {
        "kind": "markdown",
        "value": "```haxe\nvar i = \"asdf\".length;\nwhile (i-- > 0) {\n\t|\n}\n```"
      }
    },
    {
      "label": "switch",
      "sortText": "~",
      "kind": 15,
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "switch \"asdf\" {\n\tcase $0\n}",
        "range": {
          "start": {
            "character": 11,
            "line": 4
          },
          "end": {
            "character": 11,
            "line": 4
          }
        }
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "character": 11,
              "line": 4
            }
          },
          "newText": ""
        }
      ],
      "data": {
        "origin": 1
      },
      "documentation": {
        "kind": "markdown",
        "value": "```haxe\nswitch \"asdf\" {\n\tcase |\n}\n```"
      },
      "detail": "switch expr {cases...}",
      "command": {
        "title": "Trigger Suggest",
        "command": "editor.action.triggerSuggest",
        "arguments": []
      }
    },
    {
      "label": "charAt",
      "kind": 2,
      "detail": "public function charAt(index:Int):String",
      "textEdit": {
        "newText": "charAt"
      },
      "documentation": null,
      "sortText": "0000000001",
      "data": {
        "origin": 0,
        "index": 0
      }
    },
    {
      "label": "charCodeAt",
      "kind": 2,
      "detail": "public function charCodeAt(index:Int):Null<Int>",
      "textEdit": {
        "newText": "charCodeAt"
      },
      "documentation": null,
      "sortText": "0000000002",
      "data": {
        "origin": 0,
        "index": 1
      }
    },
    {
      "label": "indexOf",
      "kind": 2,
      "detail": "public function indexOf(str:String, ?startIndex:Null<Int>):Int",
      "textEdit": {
        "newText": "indexOf"
      },
      "documentation": null,
      "sortText": "0000000003",
      "data": {
        "origin": 0,
        "index": 2
      }
    },
    {
      "label": "iterator",
      "kind": 2,
      "detail": "public inline function iterator():haxe.iterators.StringIterator",
      "textEdit": {
        "newText": "iterator"
      },
      "documentation": null,
      "sortText": "0000000004",
      "data": {
        "origin": 0,
        "index": 3
      }
    },
    {
      "label": "keyValueIterator",
      "kind": 2,
      "detail": "public inline function keyValueIterator():haxe.iterators.StringKeyValueIterator",
      "textEdit": {
        "newText": "keyValueIterator"
      },
      "documentation": null,
      "sortText": "0000000005",
      "data": {
        "origin": 0,
        "index": 4
      }
    },
    {
      "label": "lastIndexOf",
      "kind": 2,
      "detail": "public function lastIndexOf(str:String, ?startIndex:Null<Int>):Int",
      "textEdit": {
        "newText": "lastIndexOf"
      },
      "documentation": null,
      "sortText": "0000000006",
      "data": {
        "origin": 0,
        "index": 5
      }
    },
    {
      "label": "length",
      "kind": 10,
      "detail": "public var length(default, null):Int",
      "textEdit": {
        "newText": "length"
      },
      "documentation": null,
      "sortText": "0000000007",
      "data": {
        "origin": 0,
        "index": 6
      }
    },
    {
      "label": "split",
      "kind": 2,
      "detail": "public function split(delimiter:String):Array<String>",
      "textEdit": {
        "newText": "split"
      },
      "documentation": null,
      "sortText": "0000000008",
      "data": {
        "origin": 0,
        "index": 7
      }
    },
    {
      "label": "substr",
      "kind": 2,
      "detail": "public function substr(pos:Int, ?len:Null<Int>):String",
      "textEdit": {
        "newText": "substr"
      },
      "documentation": null,
      "sortText": "0000000009",
      "data": {
        "origin": 0,
        "index": 8
      }
    },
    {
      "label": "substring",
      "kind": 2,
      "detail": "public function substring(startIndex:Int, ?endIndex:Null<Int>):String",
      "textEdit": {
        "newText": "substring"
      },
      "documentation": null,
      "sortText": "0000000010",
      "data": {
        "origin": 0,
        "index": 9
      }
    },
    {
      "label": "toLowerCase",
      "kind": 2,
      "detail": "public function toLowerCase():String",
      "textEdit": {
        "newText": "toLowerCase"
      },
      "documentation": null,
      "sortText": "0000000011",
      "data": {
        "origin": 0,
        "index": 10
      }
    },
    {
      "label": "toString",
      "kind": 2,
      "detail": "public function toString():String",
      "textEdit": {
        "newText": "toString"
      },
      "documentation": null,
      "sortText": "0000000012",
      "data": {
        "origin": 0,
        "index": 11
      }
    },
    {
      "label": "toUpperCase",
      "kind": 2,
      "detail": "public function toUpperCase():String",
      "textEdit": {
        "newText": "toUpperCase"
      },
      "documentation": null,
      "sortText": "0000000013",
      "data": {
        "origin": 0,
        "index": 12
      }
    }
  ]
}
```
</details>

**Comment by Jumblemuddle** [comment]
With `RUST_BACKTRACE=1`
```
thread '<unnamed>' panicked at 'Failed to parse response: Error("data did not match any variant of untagged enum CompletionResponse", line: 0, column: 0)', src/libcore/result.rs:997:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:215
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   4: rust_begin_unwind
             at src/libstd/panicking.rs:312
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::result::unwrap_failed
   7: kak_lsp::context::Context::call::{{closure}}
   8: kak_lsp::controller::start
May 30 14:39:01.609 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:160
May 30 14:39:01.609 ERRO Failed to join controller thread, module: kak_lsp::session:75
```

**Comment by Jumblemuddle** [comment]
<details>
<summary>With RUST_BACKTRACE=full</summary>

```
thread '<unnamed>' panicked at 'Failed to parse response: Error("data did not match any variant of untagged enum CompletionResponse", line: 0, column: 0)', src/libcore/result.rs:997:5
stack backtrace:
   0:     0x56409096dfb3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hb1c451488efd77c5
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x564090971601 - std::panicking::default_hook::{{closure}}::hec6c686563ccd55c
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x5640909707da - std::panicking::rust_panic_with_hook::hcc0baffa3296fdbf
                               at src/libstd/panicking.rs:215
                               at src/libstd/panicking.rs:478
   3:     0x5640909723ee - std::panicking::continue_panic_fmt::h4d85cb524d2034ea
                               at src/libstd/panicking.rs:385
   4:     0x5640909726b5 - rust_begin_unwind
                               at src/libstd/panicking.rs:312
   5:     0x56409099557b - core::panicking::panic_fmt::he94f72cd13972d6e
                               at src/libcore/panicking.rs:85
   6:     0x564090a0f6fd - core::result::unwrap_failed::hff80f0d9887dc61c
   7:     0x564090a73045 - kak_lsp::context::Context::call::{{closure}}::h3be54dcc16bf4950
   8:     0x564090a3b315 - kak_lsp::controller::start::hab1cbd614b2bd8ae
   9:     0x5640909b5c7e - std::sys_common::backtrace::__rust_begin_short_backtrace::h1b5fc459fdcc33c2
  10:     0x5640909bc134 - <F as alloc::boxed::FnBox<A>>::call_box::h3e776a6fc57dd876
  11:     0x564090977219 - std::sys::unix::thread::Thread::new::thread_start::h29aa7178eca7173a
                               at /build/rustc-1.34.0-src/src/liballoc/boxed.rs:759
  12:     0x7f751c10aef6 - start_thread
  13:     0x7f751be2a22e - __GI___clone
  14:                0x0 - <unknown>
May 30 14:40:15.795 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:160
May 30 14:40:15.795 ERRO Failed to join controller thread, module: kak_lsp::session:75
```
</details>

**Comment by ul** [comment]
Thanks for the detailed report! Yes, response doesn't comply with the spec. Offensive items miss `range` field in `textEdit`, like this:

```
    {
      "label": "charAt",
      "kind": 2,
      "detail": "public function charAt(index:Int):String",
      "textEdit": {
        "newText": "charAt"
      },
      "documentation": null,
      "sortText": "0000000001",
      "data": {
        "origin": 0,
        "index": 0
      }
    }
```

**Comment by Jumblemuddle** [comment]
I've created https://github.com/vshaxe/vshaxe/issues/350
