### ISSUE TITLE
thread main panic

### ISSUE THREAD

**Issue by danr** [ul/kak-lsp#246]
Hi ul, I'm using https://github.com/theia-ide/typescript-language-server and I get this crash:

```
Oct 09 19:37:54.395 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_TYPESCRIPT, module: kak_lsp::project_root:41
Oct 09 19:37:54.395 DEBG Routing editor request to Route { session: "262293", language: "typescript", root: "/home/dan/code/tv" }, module: kak_lsp::session:95
Oct 09 19:37:54.546 INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:20
Oct 09 19:37:54.546 INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:18
Oct 09 19:37:54.546 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:20
Oct 09 19:37:54.546 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:18
Oct 09 19:37:54.547 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:20
thread 'main' panicked at 'Box<Any>', src/thread_worker.rs:29:17
```

Let me know if there's some more info I can provide.

**Comment by danr** [comment]
Well here is some more info from another crash:

```Oct 09 19:58:30.881 ERRO failed to fill whole buffer, module: kak_lsp::language_server_transport:68
Oct 09 19:58:30.881 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:20
Oct 09 19:58:30.897 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:18
Oct 09 19:58:30.898 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:20
Oct 09 19:58:38.866 DEBG From editor: 
session   = "262293"
client    = "client0"
buffile   = "/home/dan/code/tv/bits.ts"
filetype  = "typescript"
version   = 1532
method    = "textDocument/hover"
[params.position]
line      = 28
column    = 10
, module: kak_lsp::editor_transport:125
Oct 09 19:58:38.866 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_TYPESCRIPT, module: kak_lsp::project_root:41
thread 'main' panicked at 'Box<Any>', src/thread_worker.rs:29:17
Oct 09 19:58:38.866 DEBG Routing editor request to Route { session: "262293", language: "typescript", root: "/home/dan/code/tv" }, module: kak_lsp::session:95
Oct 09 19:58:38.866 INFO Waiting for Controller to finish..., module: kak_lsp::thread_worker:18
Oct 09 19:58:38.866 INFO ... Controller terminated with err, module: kak_lsp::thread_worker:20
Oct 09 19:58:38.866 INFO Waiting for Messages to editor to finish..., module: kak_lsp::thread_worker:18
Oct 09 19:58:38.866 INFO ... Messages to editor terminated with ok, module: kak_lsp::thread_worker:20
```

**Comment by danr** [comment]
Error seems to come from from ropey actually:

```
$ RUST_BACKTRACE=full kak-lsp -vv -s 8080 -c ~/config/kak/plugins/kak-lsp/kak-lsp.toml 
Oct 13 18:24:15.574 INFO Starting main event loop, module: kak_lsp::session:29
Oct 13 18:24:17.511 INFO Starting Language server `javascript-typescript-stdio `, module: kak_lsp::language_server_transport:21
thread 'Controller' panicked at 'Attempt to index past end of slice: byte index 12, slice byte length 6', /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.1.0/src/slice.rs:190:9
stack backtrace:
   0:     0x5578a2db1b38 - backtrace::backtrace::libunwind::trace::h7b8b1b0776b7b5b3
                               at /build/rust/src/rustc-1.38.0-src/vendor/backtrace/src/backtrace/libunwind.rs:88
   1:     0x5578a2db1b38 - backtrace::backtrace::trace_unsynchronized::hf8099f03cc18ced3
                               at /build/rust/src/rustc-1.38.0-src/vendor/backtrace/src/backtrace/mod.rs:66
   2:     0x5578a2db1b38 - std::sys_common::backtrace::_print::h0921684aa16f5bcc
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5578a2db1b38 - std::sys_common::backtrace::print::h7a7b9ff69784d96e
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5578a2db1b38 - std::panicking::default_hook::{{closure}}::hc2d97891d01ebf8c
                               at src/libstd/panicking.rs:200
   5:     0x5578a2db1288 - std::panicking::default_hook::hc3aded1de8b8daef
                               at src/libstd/panicking.rs:214
   6:     0x5578a2db1288 - std::panicking::rust_panic_with_hook::h4bdd3be32f32cdb6
                               at src/libstd/panicking.rs:477
   7:     0x5578a2db0daf - std::panicking::continue_panic_fmt::h9ac850295cbe9ee6
                               at src/libstd/panicking.rs:384
   8:     0x5578a2db0d5c - std::panicking::begin_panic_fmt::hf56acb349576fa9f
                               at src/libstd/panicking.rs:339
   9:     0x5578a2c16bf2 - kak_lsp::position::kakoune_position_to_lsp::h1e1fbdb76571dfa2
  10:     0x5578a2ee2a98 - kak_lsp::controller::dispatch_editor_request::h0edfbca78600719c
  11:     0x5578a2e55ea4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a75c5cc75ee8e69
  12:     0x5578a2e2b3c8 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb6956ac7146433b4
  13:     0x5578a2ed1490 - kak_lsp::controller::start::hde70e06e4ef50a0b
  14:     0x5578a2e1d1e7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h43846122726d5c23
  15:     0x5578a2e3bff3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9f4723b4817f992e
  16:     0x5578a2dc4eef - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h171e3aea34f291c1
                               at /build/rust/src/rustc-1.38.0-src/src/liballoc/boxed.rs:787
  17:     0x5578a2dc732c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb44c85e9522da8b6
                               at /build/rust/src/rustc-1.38.0-src/src/liballoc/boxed.rs:787
  18:     0x5578a2dc732c - std::sys_common::thread::start_thread::h2b4faad4cb858842
                               at src/libstd/sys_common/thread.rs:13
  19:     0x5578a2dc732c - std::sys::unix::thread::Thread::new::thread_start::hc68200749dc7510f
                               at src/libstd/sys/unix/thread.rs:79
  20:     0x7f5e19bae57f - start_thread
  21:     0x7f5e19ac40e3 - __clone
  22:                0x0 - <unknown>
```

**Comment by ul** [comment]
Would you mind trying to add `offset_encoding = "utf-8"` to `[language.typescript]` section (or whatever it is called) in your `kak-lsp.toml`? The language server might be violating the spec, please refer https://github.com/ul/kak-lsp/#positioncharacter-interpretation for more details.

**Comment by osiox** [comment]
I did encounter this issue with typescript-language-server. Adding offset_encoding seems to fix it. I guess installing servers on wiki should be updated with offset_encoding line in kak-lsp config.

**Comment by ul** [comment]
@danr does `offset_encoding = "utf-8"` solve the issue for you as well?

**Comment by jibingeo** [comment]
I was facing same issue with https://github.com/jaredly/reason-language-server while doing `lsp-formatting`. As @ul suggested, setting `offset_encoding = "utf-8"` in `kak-lsp.toml` resolved this issue. Thanks @ul
