### ISSUE TITLE
Panic on launch when file `/tmp/kak-lsp` exists

### ISSUE THREAD

**Issue by bugabinga** [ul/kak-lsp#369]
It seems that `kak-lsp` expects to be able to create a directory `/tmp/kak-lsp`.
When that path points to a file, `kak-lsp` panics.

Reproduce:

```sh
$ rm -rf /tmp/kak-lsp
$ touch /tmp/kak-lsp
$ RUST_BACKTRACE=1 ./Workspace/kak-lsp/target/release/kak-lsp -s xxx
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: Other, messa
ge: "Not a directory" }', src/libcore/result.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /usr/src/rustc-1.41.0/vendor/backtrace/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /usr/src/rustc-1.41.0/vendor/backtrace/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1188
  14: kak_lsp::util::temp_dir
  15: kak_lsp::main
  16: std::rt::lang_start::{{closure}}
  17: main
  18: __libc_start_main
  19: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Workaround:

```sh
$ rm -rf /tmp/kak-lsp
```

Environment:

- WSL (Ubuntu 20.04)
- commit 7fcca8d7fdea7ea3f364f5098bbc8ec95655a981 (HEAD -> master, origin/master, origin/HEAD)

**Comment by topisani** [comment]
I would think this is the correct behavior... The error could maybe be formatted better, but I'm not really sure that's worth it
